export {default as Login} from './Login/Login'
export {default as Register} from './Register/Register'
export {default as Home} from './Home/Home'
export {default as Product} from './Products/Products'
export {default as CustomerHome} from './CustomerHome/CustomerHome'