export { default as AppLayout } from './template/AppLayout/AppLayout'
export { default as SignupForm } from './registration/SignupForm/SignupForm'
export { default as LoginForm } from './login/LoginForm/LoginForm'
export { default as Header } from './UserPage/Header'
export { default as Footer } from './UserPage/Footer'
export { default as PredictionForm } from './prediction/prediction'
