export const PRODUCT_ACTION_TYPES = {
  POST_PRODUCT: 'POST_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  GET_PRODUCT_LIST: 'GET_PRODUCT_LIST'
}

export const CATEGORY_ACTION_TYPES = {
  POST_CATEGORY: 'POST_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  GET_CATEGORY_LIST: 'GET_CATEGORY_LIST'
}

export const BRAND_ACTION_TYPES = {
  POST_BRAND: 'POST_BRAND',
  UPDATE_BRAND: 'UPDATE_BRAND',
  GET_BRAND_LIST: 'GET_BRAND_LIST'
}

export const REGISTRATION_ACTION_TYPES = {
  SIGNUP_USER: 'SIGNUP_USER'
}

export const LOGIN_ACTION_TYPES = {
  SIGNIN_USER: 'SIGNIN_USER'
}

export const COMMON_ACTION_TYPES = {
  REQUEST: '_REQUEST',
  SUCCESS: '_SUCCESS',
  ERROR: '_ERROR',
  CLEAR: '_CLEAR',
  SET_ALERT_REQ: '_SET_ALERT_REQ',
  SET_ALERT: '_SET_ALERT',
  CLEAR_ALERT: '_CLEAR_ALERT'
}

export const APP_ACTION_STATUS = {
    SUCCESS: 'success',
    ERROR: 'error',
    LOADING: 'loading',
    INITIAL: 'intial'
  }