import { FormValidatorFeildDto } from "./core.model";

 export interface productListDto {
    id: number,
    Location: string,
    NoOfBedRooms: number,
    NoOfBathRooms: number,
    LivingArea: number,
    LandArea: number,
    floors: number,
    School: number,
    ShappingMall: number,
    Transport: number,
    Date: string,
    CurrencyRate: number,
    Price: number,
    Link: string,
 }

 export interface ProductInfoDto {
   id?: number,
   Location: string,
   NoOfBedRooms: number | null,
   NoOfBathRooms: number | null,
   LivingArea: number | null,
   LandArea: number | null,
   floors: number | null,
   School: number | null,
   ShappingMall: number | null,
   Transport: number | null,
   Date: string,
   CurrencyRate: number | null,
   Price: number | null,
   Link: string,
 }
 export interface ProductEditDto {
   id: number,
   Location: string,
   NoOfBedRooms: number | null,
   NoOfBathRooms: number | null,
   LivingArea: number | null,
   LandArea: number | null,
   floors: number | null,
   School: number | null,
   ShappingMall: number | null,
   Transport: number | null,
   Date: string,
   CurrencyRate: number | null,
   Price: number | null,
   Link: string,
 }

 export interface ProductInitialStateDto {

  Location: FormValidatorFeildDto<string>,
  NoOfBedRooms: FormValidatorFeildDto<number | null>,
  NoOfBathRooms: FormValidatorFeildDto<number | null>,
  LivingArea: FormValidatorFeildDto<number | null>,
  LandArea: FormValidatorFeildDto<number | null>,
  floors: FormValidatorFeildDto<number | null>,
  School: FormValidatorFeildDto<number | null>,
  ShappingMall: FormValidatorFeildDto<number | null>,
  Transport: FormValidatorFeildDto<number | null>,
  Date: FormValidatorFeildDto<string>,
  CurrencyRate: FormValidatorFeildDto<number | null>,
  Price: FormValidatorFeildDto<number | null>,
  Link: FormValidatorFeildDto<string>,
 
 }
 export interface ProductUpdateStateDto {
  id:  FormValidatorFeildDto<number>,
  Location: FormValidatorFeildDto<string>,
  NoOfBedRooms: FormValidatorFeildDto<number | null>,
  NoOfBathRooms: FormValidatorFeildDto<number | null>,
  LivingArea: FormValidatorFeildDto<number | null>,
  LandArea: FormValidatorFeildDto<number | null>,
  floors: FormValidatorFeildDto<number | null>,
  School: FormValidatorFeildDto<number | null>,
  ShappingMall: FormValidatorFeildDto<number | null>,
  Transport: FormValidatorFeildDto<number | null>,
  Date: FormValidatorFeildDto<string>,
  CurrencyRate: FormValidatorFeildDto<number | null>,
  Price: FormValidatorFeildDto<number | null>,
  Link: FormValidatorFeildDto<string>,
 }