import { FormValidatorFeildDto } from "./core.model";

 export interface productListDto {
    id: number,
    location: string,
    noOfBedRooms: number,
    noOfBathRooms: number,
    livingArea: number,
    landArea: number,
    floors: number,
    school: number,
    shappingMall: number,
    transport: number,
    date: string,
    currencyRate: number,
    price: number,
    link: string,
 }

 export interface ProductInfoDto {
   id?: number,
   location: string,
   noOfBedRooms: number | null,
   noOfBathRooms: number | null,
   livingArea: number | null,
   landArea: number | null,
   floors: number | null,
   school: number | null,
   shappingMall: number | null,
   transport: number | null,
   date: string,
   currencyRate: number | null,
   price: number | null,
   link: string,
 }
 export interface ProductEditDto {
  id: number,
  location: string,
  noOfBedRooms: number | null,
  noOfBathRooms: number | null,
  livingArea: number | null,
  landArea: number | null,
  floors: number | null,
  school: number | null,
  shappingMall: number | null,
  transport: number | null,
  date: string,
  currencyRate: number | null,
  price: number | null,
  link: string,
 }

 export interface ProductInitialStateDto {

  location: FormValidatorFeildDto<string>,
  noOfBedRooms: FormValidatorFeildDto<number | null>,
  noOfBathRooms: FormValidatorFeildDto<number | null>,
  livingArea: FormValidatorFeildDto<number | null>,
  landArea: FormValidatorFeildDto<number | null>,
  floors: FormValidatorFeildDto<number | null>,
  school: FormValidatorFeildDto<number | null>,
  shappingMall: FormValidatorFeildDto<number | null>,
  transport: FormValidatorFeildDto<number | null>,
  date: FormValidatorFeildDto<string>,
  currencyRate: FormValidatorFeildDto<number | null>,
  price: FormValidatorFeildDto<number | null>,
  link: FormValidatorFeildDto<string>,
 
 }
 export interface ProductUpdateStateDto {
  id:  FormValidatorFeildDto<number>,
  location: FormValidatorFeildDto<string>,
  noOfBedRooms: FormValidatorFeildDto<number | null>,
  noOfBathRooms: FormValidatorFeildDto<number | null>,
  livingArea: FormValidatorFeildDto<number | null>,
  landArea: FormValidatorFeildDto<number | null>,
  floors: FormValidatorFeildDto<number | null>,
  school: FormValidatorFeildDto<number | null>,
  shappingMall: FormValidatorFeildDto<number | null>,
  transport: FormValidatorFeildDto<number | null>,
  date: FormValidatorFeildDto<string>,
  currencyRate: FormValidatorFeildDto<number | null>,
  price: FormValidatorFeildDto<number | null>,
  link: FormValidatorFeildDto<string>,
 }